name: HTML Validation

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install html5validator
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install html5validator

    - name: Validate HTML
      run: html5validator --root ./
